# Use the official PostgreSQL image
FROM postgres:11

# Set environment variables
ENV POSTGRES_DB soil
ENV POSTGRES_USER soiladmin
ENV POSTGRES_PASSWORD soiladmin

# Copy custom PostgreSQL configuration
# COPY soil/config/pg_hba.conf /etc/postgresql/postgresql.conf

# Copy the initialization script
COPY soil/init-soil-db.sh /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432