version: "3"

services:
  app:
    build:
      context: .
      dockerfile: soil/Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/soil
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-default_secret_key_change_me_in_production}
      - DJANGO_SETTINGS_MODULE=soil.settings.dev_docker
      - HORTPLUS_JACK_KEY=secret
      - SOIL_DB_PASSWORD=test
      - SOIL_DB_USER=test
      - SOIL_DB_NAME=soil
      - SOIL_DB_HOST=db
      - HORTPLUS_API_KEY=secret
      - HORTPLUS_METWATCH_API_KEY=secret
      - PROPERTIES_API_URL='https://staging.api.properties.hortplus.com/'
      - METWATCH_API_URL='https://staging.api.metwatch.nz/'

  db:
    build:
      context: .
      dockerfile: soil/Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=soil
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

volumes:
  postgres_data:
  static_volume:
  media_volume:
