---
- hosts: app_server
  become: yes
  gather_facts: no
  remote_user: ubuntu
  vars_files:
    - aws_keys.yml
    - vars.yml

  tasks:
    - name: Clone/pull project repo
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_root }}/src/"
        accept_hostkey: yes
      become: yes
      become_user: "{{ user_username }}"

    - name: Source the soil users .bash_profile
      shell: "source {{ project_root }}/.bash_profile"
      become: yes
      become_user: "{{ user_username }}"

    - name: Django migrate
      django_manage:
        command: migrate
        app_path: "{{ project_root }}/src/{{ project_name }}"
        pythonpath: "{{ python_path }}"
        settings: "{{ django_settings }}"
        #virtualenv: "{{ project_root }}/env/"
      become: yes
      become_user: "{{ user_username }}"

    - name: Django collect static
      django_manage:
        command: collectstatic
        app_path: "{{ project_root }}/src/{{ project_name }}"
        pythonpath: "{{ python_path }}"
        settings: "{{ django_settings }}"
        #virtualenv: "{{ project_root }}/env/"
      become: yes
      become_user: "{{ user_username }}"

    - name: Run uwsgi
      shell: "(cd {{ project_root }}/src/{{ project_name }}; uwsgi --ini config/uwsgi.ini >/dev/null 2>&1 &)"
      notify: restart nginx

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
