---
- hosts: app_server
  become: yes
  gather_facts: no
  remote_user: ubuntu
  vars_files:
    - aws_keys.yml
    - vars.yml

  tasks:
    - name: Clone/pull project repo
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_root }}/src/"
        accept_hostkey: yes
      become: yes
      become_user: "{{ user_username }}"

    - name: Write env variables to .profile of application user
      blockinfile:
        path: "{{ project_root }}/.profile"
        state: present
        create: yes
        block: |
          export HORTPLUS_JACK_KEY="{{ hortplus_jack_key }}"
          export DJANGO_SECRET_KEY="{{ django_secret_key }}"
          export SOIL_DB_PASSWORD="{{ soil_db_password }}"
          export SOIL_DB_USER="{{ soil_db_user }}"
          export SOIL_DB_NAME="{{ soil_db_name }}"
        backup: yes
      become: yes
      become_user: "{{ user_username }}"

    - name: Source the soil users .profile
      shell: ". {{ project_root }}/.profile"
      become: yes
      become_user: "{{ user_username }}"

    - name: Django migrate
      django_manage:
        command: migrate
        app_path: "{{ project_root }}/src/{{ project_name }}"
        pythonpath: "{{ python_path }}"
        settings: "{{ django_settings }}"
        #virtualenv: "{{ project_root }}/env/"
      become: yes
      become_user: "{{ user_username }}"

    - name: Django collect static
      django_manage:
        command: collectstatic
        app_path: "{{ project_root }}/src/{{ project_name }}"
        pythonpath: "{{ python_path }}"
        settings: "{{ django_settings }}"
        #virtualenv: "{{ project_root }}/env/"
      become: yes
      become_user: "{{ user_username }}"

    - name: Run uwsgi
      shell: "(cd {{ project_root }}/src/{{ project_name }}; uwsgi --ini config/uwsgi.ini >/dev/null 2>&1 &)"
      notify: restart nginx

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
