---
- hosts: app_server
  become: yes
  remote_user: ubuntu
  gather_facts: no
  vars_files:
    - aws_keys.yml
    - vars.yml

  tasks:
    - name: Change hostname
      hostname:
        name: "{{ domain_name }}"

    - name: Add host to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ domain_name }} www.{{ domain_name }}'
        state: present

    - name: Add Apt signing key for postgresql
      apt_key:
        id: 7FCC7D46ACCC4CF8
        keyserver: keyserver.ubuntu.com

    #- name: Install aptitude
    #  apt:
    #    name: aptitude
    #    state: present
    #    update_cache: yes

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    # A bit to do here, set local and set timezone is differnet for RH-Amaxoner
    #- name: Set locale
    #  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

    #- name: Set /etc/localtime
    #  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime

    # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
    #- name: Set /etc/timezone
    #  template: src=../../ansible_templates/timezone.j2 dest=/etc/timezone
    #  notify: update tzdata

    - name: Add apt repository for postgresql
      apt_repository:
        repo: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'
        update-cache: yes

    - name: Install system packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - certbot
          - git
          - nginx
          - postgresql-10
          - postgresql-client-10
          - postgresql-server-dev-10
          - python3-dev
          - python3-pip
          - python-psycopg2
          - ssl-cert
          - tzdata
          - unzip

    - name: Make sure we run python3 by changing syslink for python sudo ln -sfn /usr/bin/python3.6 /usr/bin/python. Should create lrwxrwxrwx  1 root root          18 May  3 11:00  python -> /usr/bin/python3.7
      file:
        src: /usr/bin/python3.6
        dest: /usr/bin/python
        state: link
        force: yes

    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3
        extra_args: --upgrade

    - name: Install pip3 packages
      pip:
        name: "{{ item }}"
        executable: pip3
      with_items:
        - Django==3.0.6
        - aws-psycopg2==1.1.1
        - uWSGI==2.0.19.1
        - django-address==0.2.2
        - djangorestframework==3.11.0
        - requests==2.22.0
        - django-crispy-forms==1.9.0
        - django-extensions==2.2.9
        - django-tables2==2.2.1
        - django-formtools==2.2
        - django-bootstrap-datepicker-plus==3.0.5
        - django-bootstrap4==1.1.1
        - python-dateutil==2.8.1
        - django-autocomplete-light==3.5.1

    - name: Create main directory for the project
      file:
        path: "{{ project_root }}"
        state: directory
        mode: 0775

    - name: Create Unix user group
      group:
        name: webapps
        state: present

    - name: Create Unix user
      user:
        name: "{{ user_username }}"
        shell: /bin/bash
        groups: webapps
        home: "{{ project_root }}"

    - name: Create inner directories for the project
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ project_name }}"
        group: webapps
        mode: 0775
      with_items:
        - "{{ project_root }}/src"
        - "{{ project_root }}/.ssl"
        - "{{ project_root }}/logs"

    #- name: Save ssh key to server
    #  copy: src={{ ssh_github_key }} dest={{ project_root }}/.ssh/id_rsa mode=600

    - name: Set directory permissions
      file:
        dest: "{{ project_root }}"
        owner: "{{ project_name }}"
        group: users
        recurse: yes

    - name: Write env variables to bash_profile of application user
      blockinfile:
        path: "{{ project_root }}/.bash_profile"
        state: present
        create: yes
        block: |
          export HORTPLUS_JACK_KEY="{{ hortplus_jack_key }}"
          export DJANGO_SECRET_KEY="{{ django_secret_key }}"
          export SOIL_DB_PASSWORD="{{ soil_db_password }}"
          export SOIL_DB_USER="{{ soil_db_user }}"
          export SOIL_DB_NAME="{{ soil_db_name }}"
        backup: yes

    - name: Copy PostgreSQL authentication configuration
      template:
        src: ../../ansible_templates/pg_hba.j2
        dest: /etc/postgresql/10/main/pg_hba.conf
      notify:
        - restart postgresql

    # Do we Need this? Keep it clean install for now
    #- name: Copy PostgreSQL main configuration
    #  template:
    #    src: ../../ansible_templates/postgresql.j2
    #    dest: /etc/postgresql/10/main/postgresql.conf
    #  notify:
    #    - restart postgresql

    - name: Make sure PostgreSQL server is running
      service: name=postgresql state=started

    - name: Create database user
      become_user: postgres
      postgresql_user: name={{ soil_db_user }} password={{ soil_db_password }} role_attr_flags=CREATEDB,LOGIN encrypted=yes

    - name: Create database
      become_user: postgres
      postgresql_db: name={{ soil_db_name }} owner={{ soil_db_user }}

    - name: Remove default Nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Add Nginx configuration
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: "sites-enabled"
        line: "include {{ project_root }}/src/soil/config/nginx.conf;"
        firstmatch: yes
        state: present

    - name: Install self-signed SSL certificate
      command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ domain_name }}" -days 3650 -keyout {{ project_root }}/.ssl/staging.key -out {{ project_root }}/.ssl/staging.crt

  handlers:
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart postgresql
      service: name=postgresql state=restarted

- import_playbook: deploy.yml
