- hosts: app_server
  become: yes
  remote_user: ubuntu
  gather_facts: no
  vars_files:
    - aws_keys.yml
    - vars.yml

  tasks:
    - name: Change hostname
      hostname:
        name: "{{ domain_name }}"

    - name: Add host to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ domain_name }} www.{{ domain_name }}'
        state: present

    - name: Create main directory for the project
      file:
        path: "{{ project_root }}"
        state: directory
        mode: 0775

    - name: Create Unix user group
      group:
        name: webapps
        state: present

    - name: Create Unix user
      user:
        name: "{{ user_username }}"
        shell: /bin/bash
        groups: webapps
        home: "{{ project_root }}"

    - name: Create inner directories for the project
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ project_name }}"
        group: webapps
        mode: 0775
      with_items:
        - "{{ project_root }}/.ssh"
        - "{{ project_root }}/src"
        - "{{ project_root }}/db_backups"
        - "{{ project_root }}/logs"
        - "{{ project_root }}/commands"
        - "{{ project_root }}/public_html"

    #- name: Save ssh key to server
    #  copy: src={{ ssh_github_key }} dest={{ project_root }}/.ssh/id_rsa mode=600

    - name: Set directory permissions
      file:
        dest: "{{ project_root }}"
        owner: "{{ project_name }}"
        group: users
        recurse: yes

    - name: Add Apt signing key for postgresql
      apt_key:
        id: 7FCC7D46ACCC4CF8
        keyserver: keyserver.ubuntu.com

    - name: Install aptitude
      apt: pkg={{ item }} update-cache=yes
      with_items:
        - aptitude

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    # A bit to do here, set local and set timezone is differnet for RH-Amaxoner
    #- name: Set locale
    #  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

    #- name: Set /etc/localtime
    #  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime

    # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
    #- name: Set /etc/timezone
    #  template: src=../../ansible_templates/timezone.j2 dest=/etc/timezone
    #  notify: update tzdata

    - name: Add apt repository for postgresql
      apt_repository:
        repo: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'
        update-cache: yes

    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items:
        - apache2
        - certbot
        - git
        - libapache2-mod-wsgi-py3
        - postgresql-10
        - postgresql-client-10
        - postgresql-server-dev-10
        - python3-dev
        - python3-pip
        - python3-venv
        - python-psycopg2
        - ssl-cert
        - tzdata
        - unzip

    - name: Make sure we run python3 by changing syslink for python sudo ln -sfn /usr/bin/python3.7 /usr/bin/python. Should create lrwxrwxrwx  1 root root          18 May  3 11:00  python -> /usr/bin/python3.7
      file:
        src: /usr/bin/python3.7
        dest: /usr/bin/python
        state: link
        force: yes

    - name: Install pip3 packages
      pip:
        name: "{{ packages }}"
      vars:
        packages:
        - Django==3.0.6
        - aws-psycopg2==1.1.1
        - django-address==0.2.2
        - djangorestframework==3.11.0
        - requests==2.22.0
        - django-crispy-forms==1.9.0
        - django-extensions==2.2.9
        - django-tables2==2.2.1
        - django-formtools==2.2
        - django-bootstrap-datepicker-plus==3.0.5
        - django-bootstrap4==1.1.1
        - python-dateutil==2.8.1
        - django-autocomplete-light==3.5.1

  handlers:
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

    - name: restart apache
      service: name=apache2 state=restarted
