# staging/staging/ansible/vars.yml
---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: soil

user_username: "{{ project_name }}"

# the base path to install to. You should not need to change this.
install_root: /home

project_root: "{{ install_root }}/{{ project_name }}"

# any directories that need to be added to the PYTHONPATH.
python_path: "{{ project_root }}/src/{{ project_name }}"

# the git repository URL for the project
project_repo: https://github.com/mabbettbyron/soilmoisture.git

# The value of your django project's STATIC_ROOT settings.
static_root: "{{ python_path }}/static"
media_root: "{{ python_path }}/media"

locale: en_NZ.UTF-8
timezone: Pacific/Auckland

domain_name: dev.terraprobe.mahal.co.nz
django_settings: soil.settings.dev

letsencrypt_email: "mahalsnz@gmail.com"
wsgi_file_name: wsgi_dev.py
