---
###
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: launch-wizard-1
    image: ami-0fb7513bcdc525c3b
    keypair: fruition
    region: ap-southeast-2
    count: 1
  vars_files:
    - aws_keys.yml

  tasks:
    - name: Launch the new EC2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{ count }}"
      register: ec2

    - name: Add newly created host
      add_host:
        name: "{{ item.public_ip }}"
        groups: app_server
      with_items: "{{ ec2.instances }}"

    - name: Add tag to Instance
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource: "{{ item.id }}"
        region: "{{ region }}"
        state: "present"
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Type: app_server

    - name: Wait for ssh to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: app_server
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
    - name: install apache httpd
      yum: name=httpd state=present
