---
###
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: launch-wizard-1
    image: ami-0fb7513bcdc525c3b
    keypair: fruition
    region: ap-southeast-2
    count: 1
    home_dir: /home/ec2-user
  vars_files:
    - aws_keys.yml

  tasks:
    - name: Launch the new EC2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{ count }}"
      register: ec2

    - name: Add newly created host
      add_host:
        name: "{{ item.public_ip }}"
        groups: app_server
      with_items: "{{ ec2.instances }}"

    - name: Add tag to Instance
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource: "{{ item.id }}"
        region: "{{ region }}"
        state: "present"
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Type: app_server

    - name: Wait for ssh to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: app_server
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - amazon-linux-extras
        - python3
        - git

    - name: Make sure we run python3 by changing syslink for python sudo ln -sfn /usr/bin/python3.7 /usr/bin/python. Should create lrwxrwxrwx  1 root root          18 May  3 11:00  python -> /usr/bin/python3.7
      file:
        src: /usr/bin/python3.7
        dest: /usr/bin/python
        state: link
        force: yes

    - name: Install pip3 packages
      pip:
        name: Django
        executable: pip3

    - name: pull master branch
      git:
        repo: https://github.com/mahalsnz/soilmoisture.git
        dest: /home/ec2-user/dev
#        accept_hostkey: yes

    - name: runserver on port 8000
      shell: python manage.py runserver 0.0.0.0:8000
      args:
        chdir: /home/ec2-user/dev/soil

#    - name: install ssh key
#      authorized_key:
#        user: ec2-user
#        key: "{{ lookup('file', '/home/byron/.ssh/mabbettbyron_rsa.pub') }}"
#        state: present
